### ISSUE TITLE
i think we should update docker file and donot add wordpress version in it 

### ISSUE THREAD

**Issue by hashimramzan** [WITPASS/witpass-wordpress-docker-image#5]
our docker file has 
FROM wordpress:5.2.2-php7.3-apache

we should use this way 
FROM wordpress:php7.3-apache

some other issues are there as code files update able from admin which need to be restricted

**Comment by KamranAzeem** [comment]
It may look like a good idea, but it is not. :)

When we do not specify the wordpress version, we would never know if the version is changed upstream . The docker engine will have a local copy stored as `wordpress:php7.3-apache` on the server, and whenever it goes out to docker hub, it will see that it already has an image with this (same) tag. It will (incorrectly) assume that it is the same image, and will never pull the new image - unless forced. 

It is also difficult to roll back. Say, there is a problem with `php 5.2.2`, and we need to use the older version `php 5.2.1` , which docker image do we roll back to? This would be impossible if we use this suggestion. So we would keep it as it is at the moment.

**Comment by hashimramzan** [comment]
so what if we need to move forward and have latest version of wordpress like it announced and important security update and we are using old version dessicion is yours but we should be up to date 
as in last project i update word press version and all plugins and as soon as docker restarted it removed my all updates then i have to again update everything!!!

**Comment by KamranAzeem** [comment]
This was a design choice I made and is actually best practice. We discourage people specifying docker images as "apache:latest" , etc, unless they are merely testing something. For production grade work, we use actual version numbers of the images and we upgrade to a newer version, when we know it has been out and is proving to be stable. 

Please **do not** update wordpress version from within the admin panel. This is not how we want to run these containers/services/websites. 

This reminds me to let you know that we **do not** want anyone to do **absolutely anything** inside any of the `/home/containers-data/*`  directories.

**Comment by hashimramzan** [comment]
https://www.wpbeginner.com/beginners-guide/why-you-should-always-use-the-latest-version-of-wordpress/

sir wordpress never release unsatble release anyways i face issue and described so to update a version we need to add another repo with new version if that is thing i think it will start creation of all new db and etc etc.

**Comment by KamranAzeem** [comment]
Sorry, I don't understand. 

I would suggest to please re-read my previous comment. i.e. "This was a design choice ..."

**Comment by KamranAzeem** [comment]
The Witpass wordpress docker image has now been updated to 5.2.4 . All related wordpress based websites/services have been updated to use this image.

Unfortunately, the version-tag  cannot be replaced by ":latest" , nor can be changed to ":php7.3-apache" . The full version tags - which include wordpress' verison - were put place on purpose, which help us to have trace-ability and help us answer question as: "Which exact version of wordpress are we running in our containers?" . This also helps us roll-back to previous "known/working version" if the things break in the newer versions. 

For this the following, please open a separate ticket and provide more information.
> "some other issues are there as code files update able from admin which need to be restricted"
